### Required
/run/initialize
/DetSys/world/material Vacuum

### Choose Apparatus To Build
/DetSys/app/addDiceDetector null

### Set Generator 
/DetSys/gun/position 0.0 0.0 0.0 mm
/DetSys/gun/particle e-
/DetSys/gun/efficiencyEnergy 500 keV

#/DetSys/gun/direction
#/DetSys/gun/coneMaxAngle
#/DetSys/gun/coneMinAngle
#/DetSys/gun/BeamSpot 1 mm
#/DetSys/gun/SetBeta 0.05
#/DetSys/gun/SetLifetime 1 ns

/run/beamOn 10000



